services:
  php:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
      target: dev
    # Forward ssh
    volumes:
      - .:/app
      - type: bind
        source: "${SSH_AUTH_SOCK:?SSH_AUTH_SOCK is not set}"
        target: /ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php