version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
      target: dev
    # Forward ssh
    volumes:
      - .:/app
      - ${SSH_AUTH_SOCK}:/ssh-agent # Forward SSH agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php